aws_region        = "us-east-1"
vpc_cidr          = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
instance_type     = "t2.micro"
key_pair          = "CM_keypair"
# s3_bucket_name    = "femi-intech"
